class Params:
    username = "username"
    fullname = "fullname"
    password = "password"
    profileUrl = "profile_url"
    mail = "mail"
    usersRoute = "users"
    profileData = "profile_data"
    owner = "owner"
    sentTo = "sent_to"
    hasSeen = "hasSeen"
    sentTime = "sent_time"
    message = "message"
    messages = "messages"
